import { commonStyles } from "./customStyles";

export const initialNodes = [
  {
    id: "1",
    position: { x: 25, y: 300 },
    data: { label: "Login Page 100%" },
    style: {
      ...commonStyles,
    },
    type: "input",
    sourcePosition: "right",
  },
  {
    id: "2",
    position: { x: 300, y: 300 },
    data: { label: `Home Page 99%` },
    type: "default",
    targetPosition: "left",
    style: {
      ...commonStyles,
    },
    sourcePosition: "right",
  },
  {
    id: "3",
    position: { x: 500, y: 100 },
    data: { label: `Contact Us 8%` },
    type: "default",
    targetPosition: "left",
    style: {
      ...commonStyles,
    },
    sourcePosition: "right",
  },
  {
    id: "4",
    position: { x: 500, y: 300 },
    data: { label: `Scholarships 89%` },
    type: "default",
    targetPosition: "left",
    sourcePosition: "right",
    style: {
      ...commonStyles,
    },
  },
  {
    id: "5",
    position: { x: 500, y: 500 },
    data: { label: `About us 2%` },
    type: "default",
    targetPosition: "left",
    style: {
      ...commonStyles,
    },
    sourcePosition: "right",
  },
  {
    id: "p",
    type: "group",
    // type:"output"
    data: { label: null },
    position: { x: 700, y: 50 },
    style: {
      width: 700,
      height: 600,
    },
    targetPosition: "left",
  },
  {
    id: "6",
    data: { label: "Total Views of Scholarship(100%)" },
    position: { x: 10, y: 250 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    targetPosition: "left",
    style: {
      ...commonStyles,
      height: "100px",
      width: "100px",
    },
    sourcePosition: "right",
  },
  {
    id: "7",
    data: { label: "Bookmarked" },
    position: { x: 150, y: 50 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    // draggable: false,
    style: {
      ...commonStyles,
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "8",
    data: { label: "Applied" },
    position: { x: 150, y: 200 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    draggable: false,
    style: {
      ...commonStyles,
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "9",
    data: { label: "Terms & Conditions Inquiry" },
    position: { x: 150, y: 350 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    draggable: false,
    style: {
      ...commonStyles,
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "10",
    data: { label: "Not eligible for scholarship" },
    position: { x: 150, y: 500 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    draggable: false,
    style: {
      ...commonStyles,
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "11",
    data: { label: "Saved incomplete application" },
    position: { x: 350, y: 100 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    draggable: false,
    style: {
      ...commonStyles,
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "12",
    data: { label: "Submitted application" },
    position: { x: 350, y: 300 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    // draggable: false,
    style: {
      ...commonStyles,
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "13",
    data: { label: "Failed Document Verification" },
    position: { x: 500, y: 200 },
    parentNode: "p",
    extent: "parent",
    // draggable: false,
    type: "default",
    style: {
      ...commonStyles,
      backgroundColor: "red",
      color: "white",
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
  {
    id: "14",
    data: { label: "Successfully Applied" },
    position: { x: 500, y: 400 },
    parentNode: "p",
    extent: "parent",
    type: "default",
    // draggable: false,
    style: {
      ...commonStyles,
      backgroundColor: "green",
      color: "white",
    },
    targetPosition: "left",
    sourcePosition: "right",
  },
];
